version: '3'

services:
    app:
        build: ./docker/dev/php
        volumes:
            - ./:/app
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: upload
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
    nginx:
        image: nginx:alpine
        ports:
          - 80:80
        volumes:
            - ./:/app
            - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
    dbdata: